# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# Use custom format
format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$conda
$character
"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true
[conda]
format = '[$symbol$environment](bold green) '
ignore_base = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[>](bold yellow)"
vicmd_replace_one_symbol = "[r](bold)"
vimcmd_replace_symbol = "[R](bold)"
vimcmd_visual_symbol = "[V](bold)"

[directory]
truncation_length = 5
truncation_symbol = ''
truncate_to_repo = false
style = 'bold cyan'

[env_var]
variable = 'SHELL'
default = "zsh"

[git_status]
ahead = '[â‡¡${count}](green)'
behind = '[â‡£${count}](red)'
modified = '[*](bold yellow)'
untracked = '[?](bold red)'
stashed = '[\$](cyan)'
staged = '[+](bold green)'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
format = '([\[$all_status\]]($style) )'
style = ''
disabled = false

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_commit]
only_detached = true
tag_symbol = ' ğŸ· '

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[@$hostname](purple) '
trim_at = '.companyname.com'
